<a href="https://colab.research.google.com/github/harneet862/cohort/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Why do we use Numpy over list ?
Because numpy is faster than list but why?

1.   Faster to read less bytes of memory because numpy doesnot have to store the data type
2.  We dont have to typecheck in numpy because it is homogeneous array
3.  Numpy uses contiguous memory but list is not contiguous memory which is just a contiguous block of pointers pointing to the values, therefore it requires jumping in the memory therefore it is slow
4.  Effective Cache(Speed dial for computer memory located near to CPU which means it is easier to find and uses less resources) Utilization whereas array have scattered memory therefore, the CPU has to find the individual memory blocks

How are lists different from Numpy?


1.   Lists: Insertion, deletion, appending, concatenation etc. and you can do the same with numpy as well
2.   And many more in numpy

Applications of Numpy?


*   MATLAB replacement
*   Plotting
*   Backend (For pandas)
*   Storing Images
*   Machine learning





# Loading Numpy

In [ ]:
import numpy as np

# The Basics

In [ ]:
#a = np.array([1,2,3])  one dimensional array
# We can specify that the numpy elements are int and how much memory should each element take
a = np.array([1,2,3], dtype = 'int16')
print(a)

[1 2 3]


In [ ]:
b = np.array([[9.0,8.0,7.0], [1.0, 1.5, 2.5]]) # 2D array
print(b)

[[9.  8.  7. ]
 [1.  1.5 2.5]]


In [ ]:
# Get dimension
print(a.ndim)
print(b.ndim)

1
2


In [ ]:
# Get shape (rows * coloums)
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [ ]:
# How much memory is our array taking
a.dtype

dtype('int16')

In [ ]:
#Get size(answer will be in bytes) Size of each element (in bytes): 2
print(a.itemsize)
print(b.itemsize)

2
8


In [ ]:
# Size of the list(num of elemets)
print(a.size)
print(b.size)
# Memory of the total list
print(a.nbytes)
print(b.nbytes)

3
6
6
48


# Accessing/ Changing specific elements, rows, coloumns etc

In [ ]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
a.ndim
a.shape #(rows X Coloums)
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#Get a specific element [r,c]
a[1,-2] # indexing begins at 0

13

In [ ]:
# Get a specific row
a[1]
#or
a[1, :]

array([ 8,  9, 10, 11, 12, 13, 14])

In [ ]:
#  Get a specific coloumn
a[:,1]

array([2, 9])

In [ ]:
# Startindex:endindex:stepsize
a[0,1:6:2] #Leaving one leemnt in between

array([2, 4, 6])

In [ ]:
a[1,5] = 20
print(a)

a[:, 2] = [1,2]
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [ ]:
# 3-D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#Get a specific element (work outside in)
b[0][1][0]

3

In [ ]:
b[0][1][0] = 9
print(b)

[[[1 2]
  [9 4]]

 [[5 6]
  [7 8]]]


# Initialising Different types of arrays

In [ ]:
# All 0s matrix
np.zeros((2,3)) # the size should be passed as tuple

array([[0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones((4,2,2), dtype = 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [ ]:
# Any other number
np.full((2,2), 99, dtype = 'float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [ ]:
# Any other number
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [ ]:
# Random decimal numbers
np.random.rand(3,2)

array([[0.91832573, 0.40216074],
       [0.31869278, 0.87288982],
       [0.32132155, 0.55781905]])

In [ ]:
# Random integer values
np.random.randint(4,7, size = (3,3))

array([[4, 6, 4],
       [6, 4, 6],
       [5, 6, 5]])

In [ ]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)
r1.ndim

[1 1 1 2 2 2 3 3 3]


1

In [ ]:
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3,axis = 1) #repition along the coloums which means no new row is formed
print(r1)
r1 = np.repeat(arr,3, axis = 0) # repition along the rows which means new rows are formed
print(r1)

[[1 1 1 2 2 2 3 3 3]]
[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
arr = np.zeros((5,5), dtype = 'int16')
for i in range(5):
  for j in range(5):
    if (i == 0 or j == 0) or (i == 4 or j == 4):
      arr[i][j] = 1
arr[2][2] = 9
print(arr)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [ ]:
#Trying to do the sane but without using for loop
arr1 = np.ones((5,5), dtype = 'int16')
#print(arr1)
arr = np.zeros((3,3), dtype = 'int16')
arr[1][1] = 9
#print(arr)
arr1[1:-1, 1:-1] = arr
print(arr1)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


# Be careful when copying arrays!!

In [ ]:
a = np.array([1,2,3])
b = a
b[0] = 100 # This creates a shallow copy which means any change to a changes b as well
print(a)

[100   2   3]


In [ ]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


# Mathematics

In [ ]:
a = np.array([1,2,3,4])
print(a)


[1 2 3 4]


array([3, 4, 5, 6])

In [ ]:
a+2

array([3, 4, 5, 6])

In [ ]:
a-2

array([-1,  0,  1,  2])

In [ ]:
a*2

array([2, 4, 6, 8])

In [ ]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [ ]:
a+=2
print(a)

[3 4 5 6]


In [ ]:
b = np.array([1,0,1,0])
a+b

array([4, 4, 6, 6])

In [ ]:
a ** 2

array([ 9, 16, 25, 36])

In [ ]:
# Take the si
np.sin(a)

array([ 0.14112001, -0.7568025 , -0.95892427, -0.2794155 ])

# Linear algebra

In [ ]:
a = np.ones((2,3))
print(a)
b = np.full((3,2),2)
print(b)
np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [ ]:
c = np.identity(3)
np.linalg.det(c)
# Find the determinant

1.0

# Statistics

In [ ]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [ ]:
np.min(stats, axis = 0) # this gives the row which after selecting the minimum of each coloum

array([1, 2, 3])

In [ ]:
np.max(stats)

6

In [ ]:
np.sum(stats, axis = 0)

array([5, 7, 9])

# Reorganizing arrays

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((2,2, 2)) # changing the dimensions
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2]) # vertical stack

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous

In [ ]:
filedata = np.genfromtxt('data.txt', delimiter=',') # this line converts the file into arrays
filedata.astype('int32')


#Boolean masking and advanced indexing

In [ ]:
filedata > 50


In [ ]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


[1 2 3 4 5 6 7 8 9]


In [ ]:
np.any()